# ==========================================
# BASE DE DATOS LOCAL (DEV)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5434/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# DOCUMENTACIÓN (SWAGGER) - Activado en Local
# ==========================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================
# CREDENCIALES (DEV) - Leídas del Run Configuration (IDE)
# ==========================================
groq.api.url=https://api.groq.com/openai/v1
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.1-8b-instant

logging.level.com.agrosoft.api.features.harvest=DEBUG
logging.level.com.agrosoft.api.features.ai_analysis=DEBUG

cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${API_SECRET}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==========================================
# LOGGING (DEV)
# ==========================================
logging.level.com.agrosoft.api=DEBUG
logging.level.org.springframework.security=DEBUG