spring.application.name=AgroSoft

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5434/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN DE INTELIGENCIA ARTIFICIAL (GROQ)
# ==========================================
groq.api.url=https://api.groq.com/openai/v1
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.1-8b-instant

logging.level.com.agrosoft.api.features.harvest=DEBUG
logging.level.com.agrosoft.api.features.ai_analysis=DEBUG
# ==========================================
# CONFIGURACIÓN DE CLOUDINARY
# ==========================================
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${API_SECRET}
# --- FILE UPLOAD CONFIG ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB