# ==========================================
# PUERTO DINÁMICO (RAILWAY)
# ==========================================
server.port=${PORT:8081}
server.address=0.0.0.0

# ==========================================
# BASE DE DATOS PRODUCCIÓN (RAILWAY)
# ==========================================
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# --- CONFIGURACIÓN HIKARI CP (CONNECTION POOL) ---
spring.datasource.hikari.pool-name=AgroSoftHikariPool
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ==========================================
# SEGURIDAD Y DOCUMENTACIÓN
# ==========================================
# Apagar Swagger en producción por seguridad
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# ==========================================
# CREDENCIALES
# ==========================================
groq.api.url=https://api.groq.com/openai/v1
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.1-8b-instant

cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${API_SECRET}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==========================================
# LOGGING
# ==========================================
logging.level.root=INFO
logging.level.com.agrosoft.api=INFO