# ==========================================
# CONFIGURACIÓN BASE DE LA APLICACIÓN
# ==========================================
spring.application.name=AgroSoft
spring.profiles.active=${APP_ENV:dev}

# Zona horaria unificada para evitar problemas de fechas con PostgreSQL
spring.jackson.time-zone=UTC

# Habilitar Virtual Threads (Mejora masiva de rendimiento para I/O)
spring.threads.virtual.enabled=true

# ==========================================
# CONFIGURACIÓN DE ARCHIVOS
# ==========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ==========================================
spring.datasource.driver-class-name=org.postgresql.Driver
# Desactivar OSIV (Antipatrón) para liberar conexiones a la BD rápidamente
spring.jpa.open-in-view=false